@extends('layouts.admin_layout')
@section('content')
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
    Admin <br>
@endsection